development:
  adapter: sqlite3
  database: db/db_development
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/db_test
  timeout: 5000

production:
  adapter: postgresql
  database: db_production
  timeout: 5000

aws_production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

cucumber:
  <<: *test
